# Generated by Django 3.1.7 on 2021-10-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211013_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansies',
            name='Date',
            field=models.DateField(verbose_name='Дата размещения вакансии'),
        ),
    ]
