# Generated by Django 3.1.7 on 2021-10-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211013_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='Фио')),
                ('Position', models.CharField(max_length=1000, verbose_name='Должность')),
                ('Date', models.DateTimeField(verbose_name='Дата приёма')),
                ('DateEnd', models.TimeField(verbose_name='До скольки работает')),
            ],
        ),
    ]
