# Generated by Django 3.1.7 on 2021-10-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211014_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2000, verbose_name='ФИО')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.graphic')),
            ],
        ),
    ]
