# Generated by Django 3.1.7 on 2021-10-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='Days',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.days'),
        ),
    ]
