# Generated by Django 3.1.7 on 2021-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_graphic_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='Days',
        ),
        migrations.AddField(
            model_name='graphic',
            name='Days',
            field=models.ManyToManyField(to='main.Days'),
        ),
    ]
