# Generated by Django 3.1.7 on 2021-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211015_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='DateEnd',
        ),
        migrations.AddField(
            model_name='graphic',
            name='TimeEnd',
            field=models.TimeField(auto_now=None, auto_now_add=None, blank=True, null=True, verbose_name='Время окончания работы'),
        ),
    ]
