# Generated by Django 3.2.8 on 2021-10-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211015_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=500, verbose_name='Название статьи')),
                ('Anons', models.CharField(max_length=250, verbose_name='Анонс статьи')),
                ('Image', models.ImageField(upload_to='NewsImages', verbose_name='Картинка статьи')),
                ('Text', models.TextField(verbose_name='Текст статьи')),
                ('Published', models.DateField(verbose_name='Дата написания статьи')),
            ],
        ),
    ]
