# Generated by Django 3.2.8 on 2021-10-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakansies',
            name='son',
            field=models.CharField(default='none', max_length=123, verbose_name='Овша'),
        ),
    ]
