# Generated by Django 3.2.8 on 2021-10-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_vakansies_son'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=1000, verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='DonTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Punkt', models.CharField(max_length=2000, verbose_name='Населенный пункт')),
                ('Unit', models.CharField(max_length=250, verbose_name='Единица измерения')),
                ('Price', models.CharField(max_length=1000, verbose_name='Стоимость')),
                ('Service', models.ManyToManyField(to='main.Service')),
            ],
        ),
    ]
