# Generated by Django 3.2.8 on 2021-10-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_dontarif_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
