# Generated by Django 3.2.8 on 2021-10-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activehuman',
            options={'verbose_name': 'Активный гражданин', 'verbose_name_plural': 'Активные граждане'},
        ),
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterModelOptions(
            name='dontarif',
            options={'verbose_name': 'Тариф для населения. (Производственное управление «Донецкводоканал»)', 'verbose_name_plural': 'Тарифы для населения. (Производственное управление «Донецкводоканал»)'},
        ),
        migrations.AlterModelOptions(
            name='graphic',
            options={'verbose_name': 'График приёма', 'verbose_name_plural': 'Графики приёма'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='vakansies',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.CreateModel(
            name='ZugTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Punkt', models.CharField(max_length=2000, verbose_name='Населенный пункт')),
                ('Unit', models.CharField(max_length=250, verbose_name='Единица измерения')),
                ('Price', models.CharField(max_length=1000, verbose_name='Стоимость')),
                ('Service', models.ManyToManyField(to='main.Service')),
            ],
            options={
                'verbose_name': 'Тариф для населения. (Производственное управление «Зугрэсводоканал»)',
                'verbose_name_plural': 'Тарифы для населения. (Производственное управление «Зугрэсводоканал»)',
            },
        ),
        migrations.CreateModel(
            name='AsinTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Punkt', models.CharField(max_length=2000, verbose_name='Населенный пункт')),
                ('Unit', models.CharField(max_length=250, verbose_name='Единица измерения')),
                ('Price', models.CharField(max_length=1000, verbose_name='Стоимость')),
                ('Service', models.ManyToManyField(to='main.Service')),
            ],
            options={
                'verbose_name': 'Тариф для населения. (Производственное управление «Ясиноватаяводоканал»)',
                'verbose_name_plural': 'Тарифы для населения. (Производственное управление «Ясиноватаяводоканал»)',
            },
        ),
    ]
