# Generated by Django 3.2.8 on 2021-10-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211023_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakansies',
            name='son',
        ),
    ]
