# Generated by Django 3.2.8 on 2021-10-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_vakansies_son'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='ФИО')),
                ('Number', models.CharField(max_length=1024, verbose_name='Номер телефона')),
                ('Adress', models.CharField(max_length=1024, verbose_name='Адресс проживания')),
                ('Text', models.TextField(verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'Интернет приёмная',
                'verbose_name_plural': 'Заявки в интернет приёмную',
            },
        ),
    ]
