# Generated by Django 3.2.8 on 2021-10-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_internet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048, verbose_name='Контактное лицо')),
                ('Pos', models.CharField(max_length=2048, verbose_name='Должность')),
                ('Contact', models.CharField(max_length=2048, verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='NotarialDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=3000, verbose_name='Название документа')),
                ('Document', models.FileField(upload_to='Нотариальные документы', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Нотариальный документ',
                'verbose_name_plural': 'Нотариальные документы',
            },
        ),
    ]
