# Generated by Django 3.2.8 on 2021-10-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contacts_notarialdocs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
