# Generated by Django 3.2.8 on 2021-10-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posi', models.CharField(max_length=3000, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=4000, verbose_name='ФИО сотрудника')),
                ('Contact', models.CharField(max_length=50000, verbose_name='Контакт')),
                ('Pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.posi')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
