# Generated by Django 3.2.8 on 2021-11-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_con_posi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('Text', models.TextField(verbose_name='Данные')),
                ('File', models.FileField(upload_to='OnlineFiles', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Онлайн заявка',
                'verbose_name_plural': 'Онлайн заявки',
            },
        ),
        migrations.AlterField(
            model_name='con',
            name='Pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.posi', verbose_name='Должность'),
        ),
    ]
