# Generated by Django 3.2.8 on 2021-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_electron_podrazdel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electron',
            name='File',
            field=models.FileField(blank=True, upload_to='ElectronayaPriyomnaya', verbose_name='Прикрепить необходимый файл'),
        ),
    ]
