# Generated by Django 3.2.8 on 2021-12-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_electron_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='zayavky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2000, verbose_name='ФИО')),
                ('Date', models.DateField(verbose_name='Дата')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.posi', verbose_name='К сотруднику')),
            ],
        ),
        migrations.DeleteModel(
            name='Appoitment',
        ),
    ]
