# Generated by Django 3.2.8 on 2021-12-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211218_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavky',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
