# Generated by Django 3.2.8 on 2021-12-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_zayavky_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.posi', verbose_name='Сотрудник'),
        ),
    ]
