# Generated by Django 3.2.8 on 2021-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_graphic_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavky',
            name='Date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
