# Generated by Django 3.2.8 on 2021-12-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_zayavky_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indications',
            name='Spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.podrazdel', verbose_name='Производственное управление'),
        ),
    ]
