# Generated by Django 3.1.7 on 2021-09-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rucovodstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('Avatar', models.ImageField(upload_to='Avatars', verbose_name='Фотография')),
            ],
        ),
    ]
